### ISSUE TITLE
Bug: sample is quite empty...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Spikeysanju/ZoomRecylerLayout#1]
I see this:

![image](https://user-images.githubusercontent.com/5357526/72284536-e6263e80-3649-11ea-8a5e-fc46c1d2644f.png)

**Comment by Spikeysanju** [comment]
Hello, @AndroidDeveloperLB I think you have opened the wrong module(Which is an empty app which I create to test this Library.). Kindly check below link to open the library module. In which I have written the code for Zoom Recycler Layout.  I hope it helps.
 Thanks a million!
https://github.com/Spikeysanju/ZoomRecylerLayout/tree/master/zoomrecyclerlayout

**Comment by AndroidDeveloperLB** [comment]
I didn't. I cloned from here. Even the code shows it's empty:

![image](https://user-images.githubusercontent.com/5357526/72285375-a7918380-364b-11ea-8d71-fd8b1b32d7b2.png)

And your link too:
https://github.com/Spikeysanju/ZoomRecylerLayout/blob/master/zoomrecyclerlayout/src/main/java/www/sanju/zoomrecyclerlayout/ZoomRecyclerLayout.kt

https://github.com/Spikeysanju/ZoomRecylerLayout/blob/master/app/src/main/java/www/sanju/zoomrecylerlayout/MainActivity.kt

**Comment by Spikeysanju** [comment]
@AndroidDeveloperLB I have clearly mentioned in the Readme below. That this is a Library and what is the step you have to do in implement this animation. It's a layout manager for recycler view. I hope you got my point.

**Comment by Spikeysanju** [comment]
For source code, you can see my another repo
https://github.com/Spikeysanju/Tourism

**Comment by AndroidDeveloperLB** [comment]
Why put a repository with a launch-able app that doesn't do anything, instead of a sample to it, which actually use it and shows what's on the screenshots/animation?

At the very least, put a tiny sample.

As for the new link, even there I don't see a preview :

![image](https://user-images.githubusercontent.com/5357526/72286593-1f60ad80-364e-11ea-8a99-d0be746985a0.png)

So here you put a nice preview but a sample that doesn't show anything, and there you put a sample that does something but no preview and barely even explanation about the repository...

Why 2 repositories anyway? In all repositories, people put both the library and the sample. One module for sample, and one for library...

**Comment by Spikeysanju** [comment]
Ok, will update this repo with sample code functionality!. 

Have a nice day ; )

**Comment by AndroidDeveloperLB** [comment]
OK thank you!
You are quick.

**Comment by Spikeysanju** [comment]
Thanks for your suggestion 😇
